/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    articles: Article;
    categories: Category;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en' | 'zh') | ('id' | 'en' | 'zh')[];
  globals: {
    settings: Setting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'facilities-page': FacilitiesPage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'facilities-page': FacilitiesPageSelect<false> | FacilitiesPageSelect<true>;
  };
  locale: 'id' | 'en' | 'zh';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug?: string | null;
  /**
   * Product label shown on cards (e.g., "Gudang Siap Pakai", "Kavling Siap Bangun")
   */
  label?: string | null;
  phase?: ('Tahap 1' | 'Tahap 2' | 'Luxima' | 'Kavling Industri') | null;
  type?: string | null;
  thumbnail?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Key specs shown on product cards (icon + label)
   */
  keySpecs?:
    | {
        icon?: (number | null) | Media;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Highlight specifications displayed at the top of product detail page
   */
  highlightSpecs?: {
    /**
     * e.g., "6 x 24 Meter"
     */
    dimension?: string | null;
    /**
     * e.g., "144 m²"
     */
    landArea?: string | null;
    /**
     * e.g., "126 m²"
     */
    buildingArea?: string | null;
  };
  /**
   * Full specification list (Key-Value pairs)
   */
  detailedSpecs?:
    | {
        /**
         * Spec name (e.g., "Pondasi", "Atap", "Lantai 1")
         */
        key: string;
        /**
         * Spec value (e.g., "Tiang Pancang", "UPVC 2 Layer")
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL to the 3D virtual tour
   */
  virtualTourUrl?: string | null;
  /**
   * Unit-specific facilities (icon + label)
   */
  facilities?:
    | {
        icon?: (number | null) | Media;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  callToAction?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug?: string | null;
  publicationDate?: string | null;
  /**
   * Select article category
   */
  category?: (number | null) | Category;
  thumbnail?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  authors?: (number | User)[] | null;
  relatedArticles?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  email: string;
  phone: string;
  domicile?: string | null;
  buildingSize?: ('small' | 'medium' | 'large') | null;
  serviceType?: ('full' | 'legal' | 'consult') | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  label?: T;
  phase?: T;
  type?: T;
  thumbnail?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  keySpecs?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  highlightSpecs?:
    | T
    | {
        dimension?: T;
        landArea?: T;
        buildingArea?: T;
      };
  detailedSpecs?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  shortDescription?: T;
  fullDescription?: T;
  virtualTourUrl?: T;
  facilities?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  callToAction?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publicationDate?: T;
  category?: T;
  thumbnail?: T;
  excerpt?: T;
  content?: T;
  authors?: T;
  relatedArticles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  domicile?: T;
  buildingSize?: T;
  serviceType?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteTitle?: string | null;
  topNotification?: string | null;
  contactInformation?: {
    phoneNumbers?:
      | {
          label?: string | null;
          number?: string | null;
          id?: string | null;
        }[]
      | null;
    email?: string | null;
    /**
     * Email address to receive form submissions from the website contact form
     */
    formNotificationEmail?: string | null;
    headOfficeAddress?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    marketingOfficeAddress?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    socialMediaLinks?:
      | {
          platformName?: string | null;
          url?: string | null;
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  brochure?: (number | null) | Media;
  navigation?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    companyDescription?: string | null;
    copyrightText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    backgroundVideo?: (number | null) | Media;
    mobileBackgroundVideo?: (number | null) | Media;
    fallbackImage?: (number | null) | Media;
    mobileFallbackImage?: (number | null) | Media;
    overlayOpacity?: number | null;
    headline?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    subheadline?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    primaryCta?: string | null;
    /**
     * URL for primary CTA button
     */
    primaryCtaLink?: string | null;
    secondaryCta?: string | null;
    /**
     * URL or anchor for secondary CTA button
     */
    secondaryCtaLink?: string | null;
    secondaryCtaHelperText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  mainFeature?: {
    headline?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    ctaButtonLabel?: string | null;
    ctaButtonLink?: string | null;
    stats?:
      | {
          number?: ('01' | '02' | '03' | '04') | null;
          title?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          subtitle?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          image?: (number | null) | Media;
          mobileImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    badges?:
      | {
          icon?: (number | null) | Media;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    badgesCaption?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  branding?: {
    tag?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    sectionTitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    clientLogos?:
      | {
          logo?: (number | null) | Media;
          clientName?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection?: {
    cardTitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    cardDescription?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    backgroundStyle?: ('Dark Gradient' | 'Blue Gradient' | 'Simple Black') | null;
    button?: string | null;
    /**
     * URL for CTA button
     */
    buttonLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero?: {
    backgroundImage?: (number | null) | Media;
    mobileBackgroundImage?: (number | null) | Media;
    title?: string | null;
  };
  history?: {
    headline?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  videoSection?: {
    youtubeUrl?: string | null;
    thumbnail?: (number | null) | Media;
  };
  leadership?: {
    headline?: string | null;
    description?: string | null;
    leaders?:
      | {
          name?: string | null;
          position?: string | null;
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  timeline?:
    | {
        year?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities-page".
 */
export interface FacilitiesPage {
  id: number;
  hero?: {
    backgroundImage?: (number | null) | Media;
    mobileBackgroundImage?: (number | null) | Media;
    title?: string | null;
  };
  values?: {
    headline?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    valueCards?:
      | {
          title?: string | null;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  mainServices?: {
    headline?: string | null;
    description?: string | null;
    services?:
      | {
          title?: string | null;
          subtitle?: string | null;
          icon?: (number | null) | Media;
          featuresList?:
            | {
                feature?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  topNotification?: T;
  contactInformation?:
    | T
    | {
        phoneNumbers?:
          | T
          | {
              label?: T;
              number?: T;
              id?: T;
            };
        email?: T;
        formNotificationEmail?: T;
        headOfficeAddress?: T;
        marketingOfficeAddress?: T;
        socialMediaLinks?:
          | T
          | {
              platformName?: T;
              url?: T;
              icon?: T;
              id?: T;
            };
      };
  brochure?: T;
  navigation?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        companyDescription?: T;
        copyrightText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundVideo?: T;
        mobileBackgroundVideo?: T;
        fallbackImage?: T;
        mobileFallbackImage?: T;
        overlayOpacity?: T;
        headline?: T;
        subheadline?: T;
        primaryCta?: T;
        primaryCtaLink?: T;
        secondaryCta?: T;
        secondaryCtaLink?: T;
        secondaryCtaHelperText?: T;
      };
  mainFeature?:
    | T
    | {
        headline?: T;
        description?: T;
        ctaButtonLabel?: T;
        ctaButtonLink?: T;
        stats?:
          | T
          | {
              number?: T;
              title?: T;
              subtitle?: T;
              image?: T;
              mobileImage?: T;
              id?: T;
            };
        badges?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        badgesCaption?: T;
      };
  branding?:
    | T
    | {
        tag?: T;
        sectionTitle?: T;
        description?: T;
        clientLogos?:
          | T
          | {
              logo?: T;
              clientName?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        cardTitle?: T;
        cardDescription?: T;
        backgroundStyle?: T;
        button?: T;
        buttonLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        mobileBackgroundImage?: T;
        title?: T;
      };
  history?:
    | T
    | {
        headline?: T;
        content?: T;
      };
  videoSection?:
    | T
    | {
        youtubeUrl?: T;
        thumbnail?: T;
      };
  leadership?:
    | T
    | {
        headline?: T;
        description?: T;
        leaders?:
          | T
          | {
              name?: T;
              position?: T;
              photo?: T;
              id?: T;
            };
      };
  timeline?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities-page_select".
 */
export interface FacilitiesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        mobileBackgroundImage?: T;
        title?: T;
      };
  values?:
    | T
    | {
        headline?: T;
        description?: T;
        valueCards?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  mainServices?:
    | T
    | {
        headline?: T;
        description?: T;
        services?:
          | T
          | {
              title?: T;
              subtitle?: T;
              icon?: T;
              featuresList?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}