import 'dotenv/config';
import { S3Client, PutObjectCommand, HeadObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

async function main() {
  console.log('=== S3 Production Upload Diagnostics ===');
  
  const bucketName = process.env.S3_BUCKET;
  const region = process.env.S3_REGION;
  const accessKeyId = process.env.S3_ACCESS_KEY_ID;
  const secretAccessKey = process.env.S3_SECRET_ACCESS_KEY;
  const s3Endpoint = process.env.S3_ENDPOINT;

  console.log(`Bucket Name:       ${bucketName}`);
  console.log(`Region:            ${region}`);
  console.log(`Access Key ID:     ${accessKeyId ? 'SET (' + accessKeyId.substring(0, 5) + '...)' : 'MISSING'}`);
  console.log(`Secret Access Key: ${secretAccessKey ? 'SET (' + secretAccessKey.substring(0, 5) + '...)' : 'MISSING'}`);
  console.log(`Endpoint Override: ${s3Endpoint || 'NONE'}`);

  if (!bucketName || !region || !accessKeyId || !secretAccessKey) {
    console.error('ERROR: Missing S3 environment variables.');
    process.exit(1);
  }

  // 1. Initialize Client
  console.log('\n[1/4] Initializing S3 Client...');
  let s3: S3Client;
  try {
    s3 = new S3Client({
      region,
      credentials: {
        accessKeyId,
        secretAccessKey,
      },
      ...(s3Endpoint ? { endpoint: s3Endpoint } : {}),
    });
    console.log('✓ S3 Client initialized successfully.');
  } catch (error: any) {
    console.error('✗ Failed to initialize S3 Client:', error.message || error);
    process.exit(1);
  }

  // 2. Perform test upload directly from server credentials
  const testKey = `test-upload-diagnostics-${Date.now()}.txt`;
  console.log(`\n[2/4] Attempting direct S3 PUT upload of test object "${testKey}"...`);
  try {
    const putCommand = new PutObjectCommand({
      Bucket: bucketName,
      Key: testKey,
      Body: 'This is a test upload generated by the diagnostics script.',
      ContentType: 'text/plain',
    });
    const result = await s3.send(putCommand);
    console.log('✓ Direct S3 upload succeeded!');
    console.log(`  ETag: ${result.ETag}`);
  } catch (error: any) {
    console.error('✗ Direct S3 upload failed!');
    console.error('  Error Name:', error.name || error.code || 'Unknown');
    console.error('  Message:', error.message || error);
    console.error('  Full Error Details:', error);
    console.log('\n=== HINT ===');
    console.log('This indicates that the IAM User credentials do NOT have "s3:PutObject" permission on the bucket.');
    process.exit(1);
  }

  // 3. Generate Pre-signed URL
  console.log('\n[3/4] Generating pre-signed upload URL (simulating ClientUploads flow)...');
  let presignedUrl = '';
  try {
    const uploadCommand = new PutObjectCommand({
      Bucket: bucketName,
      Key: `client-${testKey}`,
      ContentType: 'text/plain',
    });
    presignedUrl = await getSignedUrl(s3, uploadCommand, { expiresIn: 300 });
    console.log('✓ Pre-signed URL generated successfully.');
    console.log(`  URL: ${presignedUrl}`);
  } catch (error: any) {
    console.error('✗ Failed to generate pre-signed URL:', error.message || error);
    process.exit(1);
  }

  // 4. Validate the uploaded object exists (HeadObject)
  console.log('\n[4/4] Verifying the uploaded test object exists via HeadObject...');
  try {
    const headCommand = new HeadObjectCommand({
      Bucket: bucketName,
      Key: testKey,
    });
    const metadata = await s3.send(headCommand);
    console.log('✓ Object verification succeeded!');
    console.log('  Metadata:', JSON.stringify(metadata.$metadata));
    console.log('  Content Length:', metadata.ContentLength);
  } catch (error: any) {
    console.error('✗ Object verification failed:', error.message || error);
  }

  console.log('\n=== Diagnostics Summary: ALL BASIC S3 OPERATIONS WORKING SUCCESSFULLY ===');
}

main().catch((err) => {
  console.error('Unhandled script error:', err);
});
